server:
  port: 9001
spring:
  application:
    name: sentinel-nacos-datasource-demo-server
  cloud:
    nacos:
      discovery.server-addr: 127.0.0.1:8848
  profiles:
    active: dev
yxt:
  sentinel:
    transport:
      dashboard: 127.0.0.1:8080
    datasource:
      namespace: f981fdb6-c9f2-455e-814e-c48bf33ced62
      group-id: SENTINEL_GROUP
      server-addr: 127.0.0.1:8848