server:
  port: 9000
spring:
  main:
    allow-circular-references: true
  application:
    name: sentinel-nacos-starter-datasource-demo
  cloud:
    sentinel:
      web-context-unify: false # 关闭context整合 避免链路失效 默认会由context为根链路
      eager: true
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        flow-rule:
          nacos:
            data-id: ${spring.application.name}-flow-rules
            data-type: json
            namespace: 04415d0c-9d8e-4e32-81a7-c0d737bb0063
            group-id: SENTINEL_GROUP
            server-addr: 127.0.0.1:8848
            rule-type: flow
        param-flow-rule:
          nacos:
            data-id: ${spring.application.name}-param-rules
            data-type: json
            namespace: 04415d0c-9d8e-4e32-81a7-c0d737bb0063
            group-id: SENTINEL_GROUP
            server-addr: 127.0.0.1:8848
            rule-type: param-flow
        authority-rule:
          nacos:
            data-id: ${spring.application.name}-authority-rules
            data-type: json
            namespace: 04415d0c-9d8e-4e32-81a7-c0d737bb0063
            group-id: SENTINEL_GROUP
            server-addr: 127.0.0.1:8848
            rule-type: authority



